_target_: torch.optim.lr_scheduler.OneCycleLR

max_lr: 1.0e-03
epochs: ${trainer.max_epoch}
steps_per_epoch: null
total_steps: null
pct_start: 0.05
anneal_strategy: cos
div_factor: 10
last_epoch: -1
verbose: False
