_target_: projects.DC_prediction.models.model.RailModel

in_planes: 16
f_maps: 32
num_levels: 4
kernel: 5
dilation: 2 
rail_type: ${loader.dataset.rail_type}
window_length: ${loader.dataset.window_length}
out_channels: 4